name: publish packages to github maven registry on a new tag generated

on:
  release:
    types: [ created ]

jobs:
   publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
         java-version: 11

      - name: Get current Tag without v
        id: vars
        run: |
          REF=${GITHUB_REF#refs/*/}
          echo ::set-output name=tag::${REF:1}

      - name: Check tag output (DEBUG)
        env:
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          echo $TAG

      - name: Publish package to Github Packages
        run: make publish
        env:
          TAG: ${{ steps.vars.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
