name: ensure main is OK, and generates a new version depending on commits

# Trigger when merging main
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: make test

  semantic_release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Generate new version number
        run: make semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
        # If you use the github token provided by GH itself, the GH actions that depend on it (such as tag created), won't actually work:https://github:com/semantic-release/github/issues/264#issuecomment-617339717:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
